### ISSUE TITLE
gdc_loadfile is not preserving file paths

### ISSUE THREAD

**Issue by dheiman** [broadinstitute/gdctools#52] opened 2017-07-26 17:56 UTC
The loadfiles generated by `gdc_loadfile` only contain file names, but not their locations.

**Comment by noblem** [comment] 2017-09-11 22:56
This was introduced during the fix to #42, but surprisingly the regression tests did not catch it (possibly because some of the GDC data changed and the baseline test data had to be updated anyway, which would change the MD5s anyway and mask this)

**Comment by noblem** [comment] 2017-09-12 16:43
Fixed by commits https://github.com/broadinstitute/gdctools/commit/391b4257218bbac03bbc868a7858a89d335b4845 and https://github.com/broadinstitute/gdctools/commit/e4692482307698b6da02c7230afa9858c59fff91

**Closed by noblem** 2017-09-12 16:43 UTC
Labels: bug
